apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-claim
spec:
  accessMode:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: slow-storage
  selector:
    matchLabels:
      release: "stable"
    matchExpressions:
      - {key: environment, operator: In, values: [prod]}

